name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - run: echo "===== Attempt 1 ====" > arti
      - name: Archive logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: resources
          retention-days: 1
          path: arti
