name: Test
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - run: |
          mkdir artifacts
          echo "===== Attempt 1 ====" > artifacts/${GITHUB_SHA}
      - name: Archive logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ github.sha }}
          retention-days: 1
          path: artifacts/
  find:
    name: find
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Find URL
        run: >
          echo 
          "Authorization: xyz" 
          '{ "branch": "'${GITHUB_REF##*/}'", "sha": "'${GITHUB_SHA}'", "variable": { "URL": "TODO" } }'
