name: Test

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_BASE_REF}
          echo ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo ${GITHUB_SHA}
          echo ${GITHUB_HEAD_REF}
