name: Test

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'mylabel')
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: |
        mkdir artifacts
        echo ${GITHUB_REF}
        echo ${GITHUB_SHA}
